// Default Arena configuration — see spec Section 5
// All values are editable through the admin UI

export const DEFAULT_ARENA_CONFIG = {
  badges: [
    // ── Unit Performance Badges ──
    {
      id: "driveThruFlyer",
      name: "Drive-Thru Flyer",
      icon: "🏁",
      customImage: null,
      tier: "gold",
      category: "unit",
      active: true,
      desc: "DT avg under threshold — fast as the Flying W",
      metric: "dt_speed_avg",
      operator: "<",
      threshold: 240,
      unit: "seconds",
      tiebreaker: null,
      evalFrequency: "end_of_shift",
      timeWindow: "shift",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "shift_team",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "biggerBetterHour",
      name: "Bigger Better Hour",
      icon: "📈",
      customImage: null,
      tier: "silver",
      category: "unit",
      active: true,
      desc: "Sales beat last week by 20%+ in a single hour",
      metric: "sales_vs_lw_pct",
      operator: ">",
      threshold: 20,
      unit: "percent",
      tiebreaker: null,
      evalFrequency: "hourly",
      timeWindow: "hour",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "both",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "whatAnHour",
      name: "What-An-Hour!",
      icon: "🍔",
      customImage: null,
      tier: "gold",
      category: "unit",
      active: true,
      desc: "Hourly grade score 95+ — a truly outstanding hour",
      metric: "hourly_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "hourly",
      timeWindow: "hour",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "both",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "tableStakes",
      name: "Table Stakes",
      icon: "👑",
      customImage: null,
      tier: "platinum",
      category: "unit",
      active: true,
      desc: "Most transactions in a single hour — company max",
      metric: "transactions_count",
      operator: "max_company",
      threshold: 0,
      unit: "count",
      tiebreaker: null,
      evalFrequency: "end_of_day",
      timeWindow: "hour",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "company_max",
      rewardTarget: "shift_team",
      shiftCrewMode: "shift_team_named",
      cooldown: 0,
    },
    {
      id: "honeyButter",
      name: "Honey Butter",
      icon: "💰",
      customImage: null,
      tier: "platinum",
      category: "unit",
      active: true,
      desc: "Highest hourly sales in the company",
      metric: "hourly_sales",
      operator: "max_company",
      threshold: 0,
      unit: "dollars",
      tiebreaker: null,
      evalFrequency: "end_of_day",
      timeWindow: "hour",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "company_max",
      rewardTarget: "shift_team",
      shiftCrewMode: "shift_team_named",
      cooldown: 0,
    },
    {
      id: "fancyKetchup",
      name: "Fancy Ketchup",
      icon: "⭐",
      customImage: null,
      tier: "bronze",
      category: "unit",
      active: true,
      desc: "Received a 5-star Google review today",
      metric: "google_5star_count",
      operator: ">=",
      threshold: 1,
      unit: "count",
      tiebreaker: null,
      evalFrequency: "end_of_day",
      timeWindow: "day",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "unit",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "justLikeYouLikeIt",
      name: "Just Like You Like It",
      icon: "🏆",
      customImage: null,
      tier: "platinum",
      category: "unit",
      active: true,
      desc: "Best OSAT score in the company for the week",
      metric: "osat_score",
      operator: "max_company",
      threshold: 0,
      unit: "score",
      tiebreaker: { metric: "osat_survey_count", direction: "desc" },
      evalFrequency: "end_of_week",
      timeWindow: "week",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "company_max",
      rewardTarget: "unit",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "goodnessLives",
      name: "Where Goodness Lives",
      icon: "🏠",
      customImage: null,
      tier: "orange",
      category: "unit",
      active: true,
      desc: "Every hour graded A+ for the entire day — perfection",
      metric: "daily_all_hours_aplus",
      operator: "=",
      threshold: 1,
      unit: "boolean",
      tiebreaker: null,
      evalFrequency: "end_of_day",
      timeWindow: "day",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "shift_team",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },

    // ── Leader Performance Badges ──
    {
      id: "orangeSpirit",
      name: "Orange Spirit",
      icon: "🔥",
      customImage: null,
      tier: "gold",
      category: "leader",
      active: true,
      desc: "3 consecutive shifts graded 95+ — on fire",
      metric: "shift_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "end_of_shift",
      timeWindow: "rolling_shifts",
      windowDays: [] as string[],
      windowLookback: 3,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "aFrameStandard",
      name: "A-Frame Standard",
      icon: "🎯",
      customImage: null,
      tier: "platinum",
      category: "leader",
      active: true,
      desc: "Daily avg grade 85+ for 7 consecutive days",
      metric: "daily_avg_grade_score",
      operator: ">=",
      threshold: 85,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "end_of_day",
      timeWindow: "rolling_days",
      windowDays: [] as string[],
      windowLookback: 7,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "madeToOrder",
      name: "Made to Order",
      icon: "💪",
      customImage: null,
      tier: "platinum",
      category: "leader",
      active: true,
      desc: "Shift grade 95+ every day of the week — consistent excellence",
      metric: "shift_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "end_of_week",
      timeWindow: "week",
      windowDays: ["MO", "TU", "WE", "TH", "FR", "SA", "SU"],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: true,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "firstLight",
      name: "First Light",
      icon: "🌅",
      customImage: null,
      tier: "silver",
      category: "leader",
      active: true,
      desc: "Opening shift graded 95+ — setting the tone",
      metric: "shift_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "end_of_shift",
      timeWindow: "shift",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: "opening",
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "lastCall",
      name: "Last Call",
      icon: "🌙",
      customImage: null,
      tier: "silver",
      category: "leader",
      active: true,
      desc: "Closing shift graded 95+ — finishing strong",
      metric: "shift_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "end_of_shift",
      timeWindow: "shift",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: null,
      shiftFilter: "closing",
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "rushHour",
      name: "Rush Hour",
      icon: "🎪",
      customImage: null,
      tier: "gold",
      category: "leader",
      active: true,
      desc: "Hourly grade 95+ during lunch rush (11AM-1PM)",
      metric: "hourly_grade_score",
      operator: ">=",
      threshold: 95,
      unit: "score",
      tiebreaker: null,
      evalFrequency: "hourly",
      timeWindow: "hour",
      windowDays: [] as string[],
      windowLookback: 0,
      hourFilter: { start: 11, end: 13 },
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "shift_team",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
    {
      id: "communityBuilder",
      name: "Community Builder",
      icon: "🛠️",
      customImage: null,
      tier: "silver",
      category: "leader",
      active: true,
      desc: "Crew tenure score improved 10+ points over 30 days",
      metric: "tenure_score_delta",
      operator: ">=",
      threshold: 10,
      unit: "points",
      tiebreaker: null,
      evalFrequency: "end_of_week",
      timeWindow: "rolling_days",
      windowDays: [] as string[],
      windowLookback: 30,
      hourFilter: null,
      shiftFilter: null,
      requireAllDays: false,
      scope: "individual",
      rewardTarget: "leader",
      shiftCrewMode: "all_leaders",
      cooldown: 0,
    },
  ],

  streakConfig: {
    minGrade: "A",
    trackBy: "both",
    resetOn: "below_threshold",
    weekDefinition: ["MO", "TU", "WE", "TH", "FR", "SA", "SU"],
    milestones: [
      { days: 3, name: "Warming Up", icon: "🔥", tier: "bronze", notify: true, rewardTarget: "leader" },
      { days: 7, name: "On the Grill", icon: "⚡", tier: "silver", notify: true, rewardTarget: "leader" },
      { days: 14, name: "Sizzling", icon: "🌟", tier: "gold", notify: true, rewardTarget: "leader" },
      { days: 30, name: "Orange Legend", icon: "👑", tier: "platinum", notify: true, rewardTarget: "both" },
    ],
  },

  shiftTeamConfig: {
    defaultCrewMode: "all_leaders",
    roleHierarchy: ["Manager", "Shift Supervisor"],
    displayFormat: "team_named",
    teamNameTemplate: "{store} {shift_type} Crew — {date}",
  },

  notifications: {
    channels: { email: true, sms: false, slack: false },
    autoMessages: [
      {
        id: "badge_earned",
        trigger: "badge_earned",
        enabled: true,
        template: "🏅 {leader_name} earned {badge_name} at {store}! {badge_desc}",
        recipients: "leader+mul",
      },
      {
        id: "team_badge",
        trigger: "team_badge_earned",
        enabled: true,
        template: "🏅 Shift Team earned {badge_name} at {store}! Team: {team_names}. {badge_desc}",
        recipients: "shift_team+mul",
      },
      {
        id: "streak_milestone",
        trigger: "streak_milestone",
        enabled: true,
        template: "🔥 {leader_name} hit a {streak_days}-day streak — {milestone_name}!",
        recipients: "leader+mul+company",
      },
      {
        id: "record_broken",
        trigger: "record_broken",
        enabled: true,
        template: "🏆 NEW RECORD at {store} — {record_type}: {record_value}. Team: {team_names}",
        recipients: "company",
      },
      {
        id: "streak_broken",
        trigger: "streak_broken",
        enabled: true,
        template: "⚠️ {leader_name}'s {streak_days}-day streak ended at {store}. Today: {today_grade}.",
        recipients: "mul_only",
      },
      {
        id: "daily_summary",
        trigger: "daily_eod",
        enabled: true,
        template: "📊 MWB Arena Daily — {date}\nTop Leader: {top_leader}\nTop Unit: {top_unit}\nBadges: {badge_count} | Streaks: {streak_count}",
        recipients: "mul+ceo",
      },
    ],
    recipientGroups: {
      leader: "Individual leader",
      shift_team: "All leaders on the qualifying shift",
      unit: "All leaders at that store",
      mul: "Multi-unit leader for that store",
      ceo: "CEO / Owner",
      company: "All leaders across all 21 units",
      "leader+mul": "Leader + MUL",
      "shift_team+mul": "Shift team + MUL",
      "leader+mul+company": "Leader + MUL + everyone",
      mul_only: "Only MUL",
      "mul+ceo": "MULs + CEO",
    },
  },

  peakHours: [
    { name: "Lunch Rush", start: 11, end: 13 },
    { name: "Dinner Rush", start: 17, end: 19 },
  ],

  gradeThresholds: { "A+": 97, A: 90, B: 80, C: 70, D: 60, F: 0 },
  fiscalWeekStart: "MO",
};
